#!/bin/sh
set -x
rm -rf tmp_template;
wget https://github.com/edwrodrig/template_composer_basic/blob/master/temple.phar;
git clone --single-branch https://github.com/edwrodrig/template_composer_basic.git -b template tmp_template;
php temple.phar $1 $2 tmp_template $2;
rm -rf tmp_template;
rm -rf temple.phar
